/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import conexionsql.T_Productos;
import conexionsql.T_Ventas;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Tabla_Ventas extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    Connection conn = null;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form Tabla_Ventas
     */
    public Tabla_Ventas() {
        initComponents();
        String ids [] = {"Id", "Cliente", "Empleado", "Producto", "Precio","Cantiad"};
        modelo.setColumnIdentifiers(ids);
        tablaventas.setModel(modelo);
        getConnection();
    }
    public Connection getConnection(){
        try {
            Class.forName("java.sql.DriverManager");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/productos?useSSL=false","root","");
            if(conn !=null){
               System.out.println();
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showConfirmDialog(null,"Ocurrior un error al conectarse a la BD");
            System.err.println("Error:.." + e.getMessage());
        }
          return conn;
    }   
    
    
     public void limpiando(){
        id.setText("");
        cliente.setText("");
        empleado.setText("");
        producto.setText("");
        precio.setText("");
        cantidad.setText("");
    }
    
    public void agregandodatos(){
        int el_id = Integer.parseInt(id.getText());
        int el_cliente = Integer.parseInt(cliente.getText());
        int el_empleado = Integer.parseInt(empleado.getText());
        String el_producto = producto.getText();
        int el_precio = Integer.parseInt(precio.getText());
        int la_cantidad = Integer.parseInt(cantidad.getText());
        
         //para agregar a la tabla
        modelo.addRow(new Object[] {el_id, el_cliente, el_empleado, el_producto, el_precio, la_cantidad});
        limpiando();
        
        //agregand  la base de datos
        T_Ventas insert = new T_Ventas();
        insert.Insert(el_id, el_cliente, el_empleado, el_producto, el_precio, la_cantidad);
        
    }
    
   public void actualizar(){
    int selectedRow = tablaventas.getSelectedRow();

    if (selectedRow != -1) {
        int el_id = Integer.parseInt(id.getText());
        int el_cliente = Integer.parseInt(cliente.getText());
        int el_empleado = Integer.parseInt(empleado.getText());
        String el_producto = producto.getText();
        int el_precio = Integer.parseInt(precio.getText());
        int la_cantidad = Integer.parseInt(cantidad.getText());

        //verificar con un condicional que los campos no estén vacíos
        modelo.setValueAt(el_id, selectedRow, 0);
        modelo.setValueAt(el_cliente, selectedRow, 1);
        modelo.setValueAt(el_empleado, selectedRow, 2);
        modelo.setValueAt(el_producto, selectedRow, 3);
        modelo.setValueAt(el_precio, selectedRow, 4);
        modelo.setValueAt(la_cantidad, selectedRow, 5);

        //insertando valores en la base de datos de las ventas
        T_Ventas update = new T_Ventas();
        update.Update(el_id, el_cliente, el_empleado, el_producto, el_precio, la_cantidad);
    } else {
        JOptionPane.showInternalMessageDialog(null, "Por favor, selecciona una fila para actualizar.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        superior = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        botones_acciones = new javax.swing.JPanel();
        btnlimpiar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btninsertar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        empleado = new javax.swing.JTextField();
        producto = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmbx_filtro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(0, 255, 0));
        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Titulo.setText("Tabla Ventas");
        superior.add(Titulo);

        getContentPane().add(superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 17, 260, 30));

        btnlimpiar.setText("Limpiar datos");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        botones_acciones.add(btnlimpiar);

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        botones_acciones.add(btnactualizar);

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });
        botones_acciones.add(btninsertar);

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        botones_acciones.add(btneliminar);

        getContentPane().add(botones_acciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 410, 50));

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 6, -1, 40));

        tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_venta", "Id_cliente", "Id_empleado", "Nombre_producto", "Precio", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tablaventas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 644, 180));
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 140, 30));
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 110, -1));
        getContentPane().add(empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 100, -1));
        getContentPane().add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 110, -1));

        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, -1));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 100, -1));

        jButton1.setText("buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 80, 30));

        cmbx_filtro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbx_filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IdVenta", "IdCliente", "IdEmpleado", "NombreProducto", "Precio", "Cantidad" }));
        cmbx_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_filtroActionPerformed(evt);
            }
        });
        getContentPane().add(cmbx_filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
     limpiando();
     modelo.setRowCount(0);

    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        agregandodatos();
      
   
    }//GEN-LAST:event_btninsertarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        this.dispose();
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // metodo para actualizar
        actualizar();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
      
  
        if (id.getText() == null || id.getText().isEmpty()) {
             modelo.removeRow(tablaventas.getSelectedRow()); //para eliminar la fila
        }else{
             try {
            modelo.removeRow(tablaventas.getSelectedRow());
        } catch (Exception e) {}
            T_Ventas del = new T_Ventas();
            del.Delete(Integer.parseInt(id.getText())); //eliminando de la base  de datoss
        }
    }//GEN-LAST:event_btneliminarActionPerformed
     String filtro(){
    if(cmbx_filtro.getSelectedIndex()==0){
    return "Id";
    }else if(cmbx_filtro.getSelectedIndex()==1){
        return "IdCliente";
    }else if(cmbx_filtro.getSelectedIndex()==2){
    return "IdEmpleado";
    }
    else if(cmbx_filtro.getSelectedIndex()==3){
        return "NOmbreProducto";
    }
    else if(cmbx_filtro.getSelectedIndex()==4){
        return "Precio";
    }else {
     return "Cantidad";
    }
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtbuscar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe de ingresar el dato a buscar");

        }else{
            //Declaramos un DefaultTableModelpara enviar el nuevo modelo a la Tabla
            DefaultTableModel modelo= (DefaultTableModel) tablaventas.getModel();
            //Le decimos que comience en 0
            modelo.setRowCount(0);
            //Declaramos un arreglo para almacenar los datos
            String[] datos= new String[5];

            //Obenter el dato a bsucar
            String dato= txtbuscar.getText().trim();

            int cont=0;
            try {
                pst= conn.prepareStatement("select * from ventas where " + filtro() + " like '%" + dato + "%'");
                rs=pst.executeQuery();

                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[4]=rs.getString(4);
                    datos[5]=rs.getString(5);
                    //Enviamos el vector al modelo o tabla
                    modelo.addRow(datos);
                    //Incementa cada vez que encuentra un valor
                    cont++;
                    if(cont>0){
                        tablaventas.setModel(modelo);
                    }else{
                        JOptionPane.showMessageDialog(null, "No se encontro resultados en la busqueda");

                    }
                }
            }catch ( SQLException e) {
                JOptionPane.showMessageDialog(null,"Ocurrio un error al hacer la busqueda de los datos del usuario");
                System.err.println("Error" + e.getMessage());
            }finally{
                try {
                    pst.close();
                } catch (Exception e) {
                    System.err.println("Error" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbx_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_filtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbx_filtroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla_Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel botones_acciones;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField cliente;
    private javax.swing.JComboBox<String> cmbx_filtro;
    private javax.swing.JTextField empleado;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField producto;
    private javax.swing.JPanel superior;
    private javax.swing.JTable tablaventas;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
